testing on VM

diff --git a/postinstall b/postinstall
--- a/postinstall
+++ b/postinstall
@@ -80,18 +80,18 @@ echo -ne "
                                   Installing packages
 ------------------------------------------------------------------------------------------
 "
-if [[ ! -f "packages" ]]; then
-  echo "Error: packages file not found."
-  exit 1
-fi
-
-while read line
-do
-  if [[ $line == "" ]] || [[ $line == \#* ]]; then
-    continue
-  fi
-  xbps-install -S -y "$line"
-done < packages
+# if [[ ! -f "packages" ]]; then
+#   echo "Error: packages file not found."
+#   exit 1
+# fi
+#
+# while read line
+# do
+#   if [[ $line == "" ]] || [[ $line == \#* ]]; then
+#     continue
+#   fi
+#   xbps-install -S -y "$line"
+# done < packages
 
 echo -ne "
 ------------------------------------------------------------------------------------------
